pub mod coloring;
pub mod connectivity;
pub mod algo_traits;
pub mod search;
pub mod search_visitors;
pub mod distance;
pub mod trees;
pub mod gonality;
pub mod matchings;
pub mod planarity;
#[cfg(feature = "wgpu")]
pub mod isomorphism;
